function [muscleRecord, ...
        muscleStateRecord, ...
        muscleState0, ...
        skeletonPose, ...
        torqueRecord, ...
        interForce] = initialization(simSpan, simT, muscleNum, initArch)

muscleRecord        = init_record(simSpan(2), simT, muscleNum); % 初始化肌肉长度、角度、兴奋、激活、力等，是个结构体数组
muscleStateRecord   = init_muscleState(simSpan(2), simT, muscleNum, initArch); % 初始化肌肉长度、速度，仅用于计算肌肉激活
muscleState0        = zeros(muscleNum, 1); % 肌纤维初始长度 initial fiber length
skeletonPose        = init_skeletonPose(simSpan(2), simT, initArch); % 存储骨骼姿态和速度，并初始化t=0时刻的值
torqueRecord        = init_torqueRecord(simSpan(2), simT); % 存储关节力矩
interForce          = init_interForce(simSpan(2), simT); % 存储交互摩擦力

end